### ISSUE TITLE
Latest upstream-registry-builder contains a bad opm executable

### ISSUE THREAD

**Issue by bfabec** [operator-framework/operator-registry#238]
Recently our operator builds that are generated by operator-sdk (image/bundle) and opm (index) have been failing due the following error: `panic: generate flag redefined: package`

I was able to trace the problem down to the `opm` binary contained within the quay.io/operator-framework/upstream-registry-builder:latest image that was pushed a day ago. If you pull that image and run the `opm` command, you will see the failure. The failure doesn't occur with the 1.6.1 version of the builder.

https://quay.io/repository/operator-framework/upstream-registry-builder/manifest/sha256:9c3fabac7d8813d9c9df9988bb08d703846ed3ddb964244bbe9e156a73ba0a86

```
docker run -it quay.io/operator-framework/upstream-registry-builder:latest sh
/build # ls
Makefile  bin       cmd       go.mod    pkg       vendor
/build # cd bin
/build/bin # ls
appregistry-server  configmap-server    initializer         opm                 registry-server
/build/bin # ./opm
panic: generate flag redefined: package

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc0000cb400, 0xc000122f00)
	/build/vendor/github.com/spf13/pflag/flag.go:848 +0x807
github.com/spf13/pflag.(*FlagSet).VarPF(0xc0000cb400, 0x1b05b40, 0x26e4000, 0x18aff2d, 0x7, 0x18aac4e, 0x1, 0x1920db1, 0x86, 0xc0000c9cc0)
	/build/vendor/github.com/spf13/pflag/flag.go:831 +0x10b
github.com/spf13/pflag.(*FlagSet).VarP(...)
	/build/vendor/github.com/spf13/pflag/flag.go:837
github.com/spf13/pflag.(*FlagSet).StringVarP(0xc0000cb400, 0x26e4000, 0x18aff2d, 0x7, 0x18aac4e, 0x1, 0x0, 0x0, 0x1920db1, 0x86)
	/build/vendor/github.com/spf13/pflag/string.go:42 +0xad
github.com/operator-framework/operator-registry/cmd/opm/alpha/bundle.newBundleGenerateCmd(0x18a8aa0)
	/build/cmd/opm/alpha/bundle/generate.go:36 +0x21f
github.com/operator-framework/operator-registry/cmd/opm/alpha/bundle.NewCmd(0x18a8aa0)
	/build/cmd/opm/alpha/bundle/cmd.go:14 +0x9f
github.com/operator-framework/operator-registry/cmd/opm/alpha.NewCmd(0xc000449400)
	/build/cmd/opm/alpha/cmd.go:15 +0x82
main.main()
	/build/cmd/opm/main.go:27 +0xbb
/build/bin # ls -l
total 168272
-rwxr-xr-x    1 root     root      38997816 Mar 27 15:59 appregistry-server
-rwxr-xr-x    1 root     root      38230080 Mar 27 15:59 configmap-server
-rwxr-xr-x    1 root     root      25554128 Mar 27 15:59 initializer
-rwxr-xr-x    1 root     root      43325392 Mar 27 15:59 opm
-rwxr-xr-x    1 root     root      26195824 Mar 27 15:59 registry-server
/build/bin # 
```

**Comment by Bowenislandsong** [comment]
This issue if due to the lastest commit which is now reverted. https://github.com/operator-framework/operator-registry/pull/239

**Comment by Bowenislandsong** [comment]
A fix for the error also exist here: https://github.com/operator-framework/operator-registry/pull/240/files

**Comment by ecordell** [comment]
Sorry for the inconvenience, a new latest image is building right now which should not have this issue. Please re-open this if the new image does not fix the issue.

**Comment by bfabec** [comment]
Verified fixed now, thanks @Bowenislandsong @ecordell !
